# Generated by Django 3.0.4 on 2020-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(2, 'Read'), (1, 'Now')], default=1),
        ),
    ]
